-- Clear existing products and insert new enhanced data
DELETE FROM products;

-- Insert enhanced products from CSV with descriptions, colors, and image mappings
INSERT INTO products (name, description, category, status, sku, price, buy_link, image_url, group_name, color, hex_color) VALUES
-- Accessories
('Divider', 'Perfectly portion your supplements and powders with our premium divider. Designed to fit seamlessly in your Thrive water bottle, creating separate compartments for different ingredients.', 'Accessories', 'Removal Requested', 'O-DI', 8.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/divider-odi/', '/product-images/O-DI.png', 'Divider', NULL, NULL),
('Ice Molds', 'Create perfectly round ice cubes that enhance your hydration experience. Our silicone molds produce crystal-clear ice that melts slower, keeping drinks cold without diluting flavor.', 'Accessories', 'Removal Requested', 'O-IM', 19.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/ice-molds-oim/', '/product-images/O-IM.png', 'Ice Molds', NULL, NULL),
('Shaker Ball', 'Premium stainless steel shaker ball for smooth, lump-free mixing. The innovative design ensures perfect protein shake consistency every time.', 'Accessories', 'Removal Requested', 'O-SB', 7.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/shaker-ball-osb/', '/product-images/O-SB.png', 'Shaker Ball', NULL, NULL),
('The Anchor (Snack Compartment)', 'Revolutionary 2-in-1 design featuring a dedicated snack compartment alongside your hydration. Perfect for nuts, protein bars, or supplements on the go.', 'Accessories', 'Removal Requested', 'O-AN', 12.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-anchor-snack-compartment-oan/', '/product-images/O-AN.png', 'The Anchor', 'Snack Compartment', NULL),

-- Lids
('The Snow Cap (Modified Lid)', 'Engineered for perfect flow control and leak-proof performance. The modified design provides enhanced insulation and a comfortable drinking experience.', 'Accessories', 'Removal Requested', 'CA-SC', 14.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-snow-cap-modified-lid-casc/', '/product-images/CA-SC.png', 'The Snow Cap', 'Modified Lid', NULL),

-- Electrolytes - Surge IV Series
('Surge IV (Blue Razzberry)', 'Explosive blue raspberry flavor with electrolyte blend. Rapid hydration with bold, tangy taste that fuels your performance and recovery.', 'Wellness', 'Removal Requested', 'SU-EL-1', 29.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/surge-iv-blue-razzberry-suel1/', '/product-images/SU-EL-1.png', 'Surge IV', 'Blue Razzberry', '#0066FF'),
('Surge IV (Fruit Punch)', 'Classic fruit punch explosion with electrolyte power. Timeless tropical blend delivering essential minerals for peak hydration.', 'Wellness', 'In Store', 'SU-EL-2', 29.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/surge-iv-fruit-punch-suel2/', '/product-images/SU-EL-2.png', 'Surge IV', 'Fruit Punch', '#FF6B35'),
('Surge IV (Lemonade)', 'Refreshingly tart lemonade with electrolyte infusion. Zesty citrus burst that quenches thirst and replenishes vital minerals.', 'Wellness', 'Removal Requested', 'SU-EL-3', 29.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/surge-iv-lemonade-suel3/', '/product-images/SU-EL-3.png', 'Surge IV', 'Lemonade', '#FFD700'),
('Surge IV (Pina Colada)', 'Tropical pina colada escape with electrolytes. Creamy coconut and pineapple transport you to paradise while hydrating your body.', 'Wellness', 'Removal Requested', 'SU-EL-4', 29.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/surge-iv-pina-colada-suel4/', '/product-images/SU-EL-4.png', 'Surge IV', 'Pina Colada', '#F0E68C'),
('Surge IV (Strawberry)', 'Sweet strawberry bliss with electrolyte boost. Ripe, juicy flavor that makes hydration your favorite moment of the day.', 'Wellness', 'In Store', 'SU-EL-5', 29.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/surge-iv-strawberry-suel5/', '/product-images/SU-EL-5.png', 'Surge IV', 'Strawberry', '#FF69B4'),
('Surge IV (Tropical Vibes)', 'Exotic tropical fusion with electrolyte power. Pineapple, mango, and passion fruit create a vacation in every sip.', 'Wellness', 'Removal Requested', 'SU-EL-6', 29.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/surge-iv-tropical-punch-suel6/', '/product-images/SU-EL-6.png', 'Surge IV', 'Tropical Vibes', '#FF7F50'),
('Surge IV (Cucumber Lime)', 'Cool cucumber lime refreshment with electrolytes. Crisp, clean, and incredibly hydrating - perfect for post-workout recovery.', 'Wellness', 'Removal Requested', 'SU-EL-7', 29.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/surge-iv-cucumber-lime-suel7/', '/product-images/SU-EL-7.png', 'Surge IV', 'Cucumber Lime', '#90EE90'),
('Surge IV (Apple Cider)', 'Warm apple cider comfort with electrolyte benefits. Autumn-spiced hydration that feels like home while fueling your adventures.', 'Wellness', 'Removal Requested', 'SU-EL-8', 29.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/surge-iv-apple-cider-suel8/', '/product-images/SU-EL-8.png', 'Surge IV', 'Apple Cider', '#D2691E'),
('Surge IV (Assorted)', 'Variety pack of all your favorite Surge IV flavors. Perfect for those who love options and want to experience the full range.', 'Wellness', 'Removal Requested', 'SU-EL-9', 34.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/surge-iv-assorted-suel9/', '/product-images/SU-EL-2.png', 'Surge IV', 'Assorted', '#FF6B35'),
('Surge IV (Cranberry)', 'Tart cranberry burst with electrolyte power. Bold, antioxidant-rich flavor that supports your active lifestyle.', 'Wellness', 'Removal Requested', 'SU-EL-10', 29.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/surge-iv-cranberry-suel10/', '/product-images/SU-EL-10.png', 'Surge IV', 'Cranberry', '#DC143C'),

-- Electrolytes - Supply Packs
('Electrolytes - Single Flavor - One year Supply', 'Bulk supply of your favorite single flavor. 365 days of premium electrolyte hydration in one convenient package.', 'Wellness', 'In Store', 'SS-E-1', 299.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/electrolytes-single-flavor-one-year-supply-sse1/', '/product-images/SU-EL-2.png', 'Electrolytes Supply', 'Single Flavor', '#FF6B35'),
('Electrolytes - Assorted Flavor - One year Supply', 'Ultimate variety pack with all flavors. Year-round hydration with endless flavor options to match your mood.', 'Wellness', 'In Store', 'SS-E-2', 349.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/electrolytes-assorted-flavor-one-year-supply-sse2/', '/product-images/SU-EL-2.png', 'Electrolytes Supply', 'Assorted', '#FF7F50'),

-- Supplements - Peak Protein Series
('Peak Powder (Chocolate)', 'Rich, decadent chocolate protein powder. Premium whey blend with 25g protein per serving for muscle recovery and growth.', 'Wellness', 'In Store', 'SU-PR-1', 49.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/peak-powder-chocolate-supr1/', '/product-images/SU-PR-1.png', 'Peak Protein', 'Chocolate', '#3E2723'),
('Peak Powder (Vanilla)', 'Smooth, creamy vanilla protein perfection. Clean, versatile flavor that mixes perfectly in shakes, smoothies, and recipes.', 'Wellness', 'In Store', 'SU-PR-2', 49.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/peak-powder-vanilla-supr2/', '/product-images/SU-PR-2.png', 'Peak Protein', 'Vanilla', '#F3E5AB'),

-- Water Bottles - Glacier Series
('The Glacier (Black) w. Ice Cap', 'Sleek black Glacier bottle with premium Ice Cap lid. 40oz of sophisticated hydration with advanced temperature retention.', 'Water Bottles', 'In Store', 'BO-41', 99.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-glacier-black-w-ice-cap-bo41/', '/product-images/BO-41.png', 'The Glacier', 'Black', '#000000'),
('The Glacier (Brown) w. Ice Cap', 'Earthy brown Glacier bottle with Ice Cap technology. Rich, natural tone that complements your active lifestyle.', 'Water Bottles', 'In Store', 'BO-42', 99.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-glacier-brown-w-ice-cap-bo42/', '/product-images/BO-42.png', 'The Glacier', 'Brown', '#8B4513'),
('The Glacier (Frost Blue) w. Ice Cap', 'Cool frost blue Glacier with Ice Cap system. Icy blue hue that embodies peak hydration performance.', 'Water Bottles', 'In Store', 'BO-43', 99.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-glacier-frost-blue-w-ice-cap-bo43/', '/product-images/BO-43.png', 'The Glacier', 'Frost Blue', '#87CEEB'),
('The Glacier (Maroon) w. Ice Cap', 'Bold maroon Glacier bottle with Ice Cap. Deep, rich color that stands out while delivering premium hydration.', 'Water Bottles', 'In Store', 'BO-44', 99.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-glacier-maroon-w-ice-cap-bo44/', '/product-images/BO-44.png', 'The Glacier', 'Maroon', '#800000'),
('The Glacier (Orange) w. Ice Cap', 'Vibrant orange Glacier with Ice Cap technology. Energetic color that matches your active, on-the-go lifestyle.', 'Water Bottles', 'In Store', 'BO-45', 99.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-glacier-orange-w-ice-cap-bo45/', '/product-images/BO-45.png', 'The Glacier', 'Orange', '#FFA500'),
('The Glacier (White) w. Ice Cap', 'Pure white Glacier bottle with Ice Cap. Clean, minimalist design that represents the pinnacle of hydration.', 'Water Bottles', 'In Store', 'BO-46', 99.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-glacier-white-w-ice-cap-bo46/', '/product-images/BO-46.png', 'The Glacier', 'White', '#FFFFFF'),
('The Glacier (Santa Sleigh) w. Ice Cap', 'Festive Santa sleigh design with Ice Cap. Holiday spirit meets premium hydration in this limited edition.', 'Water Bottles', 'In Store', 'BO-47', 99.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-glacier-santa-sleigh-w-ice-cap-bo47/', '/product-images/BO-47.png', 'The Glacier', 'Santa Sleigh', '#FF0000'),
('The Glacier (Rudolph Red) w. Ice Cap', 'Cheerful Rudolph red Glacier with Ice Cap. Holiday edition that brings joy to your hydration routine.', 'Water Bottles', 'In Store', 'BO-48', 99.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-glacier-rudolph-red-w-ice-cap-bo48/', '/product-images/BO-48.png', 'The Glacier', 'Rudolph Red', '#FF0000'),
('The Glacier (Iced Cookie) w. Ice Cap', 'Sweet iced cookie design with Ice Cap. Festive limited edition that makes hydration feel like a treat.', 'Water Bottles', 'In Store', 'BO-49', 99.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-glacier-iced-cookie-w-ice-cap-bo49/', '/product-images/BO-49.png', 'The Glacier', 'Iced Cookie', '#DEB887'),
('The Glacier (Christmas Tree) w. Ice Cap', 'Merry Christmas tree Glacier with Ice Cap. Holiday celebration in bottle form with premium features.', 'Water Bottles', 'In Store', 'BO-50', 99.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-glacier-christmas-tree-w-ice-cap-bo50/', '/product-images/BO-50.png', 'The Glacier', 'Christmas Tree', '#228B22'),

-- Water Bottles - Iceberg Series  
('The Iceberg (Black) w. Ice Cap', 'Sleek black Iceberg with Ice Cap. Compact 32oz design with premium insulation and professional appearance.', 'Water Bottles', 'In Store', 'BO-31', 69.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-iceberg-black-w-ice-cap-bo31/', '/product-images/BO-31.png', 'The Iceberg', 'Black', '#000000'),
('The Iceberg (Brown) w. Ice Cap', 'Rich brown Iceberg with Ice Cap. Earthy tone that combines style with functionality.', 'Water Bottles', 'In Store', 'BO-32', 69.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-iceberg-brown-w-ice-cap-bo32/', '/product-images/BO-32.png', 'The Iceberg', 'Brown', '#8B4513'),
('The Iceberg (Frost Blue) w. Ice Cap', 'Cool frost blue Iceberg with Ice Cap. Refreshing blue that embodies crisp hydration.', 'Water Bottles', 'In Store', 'BO-33', 69.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-iceberg-frost-blue-w-ice-cap-bo33/', '/product-images/BO-33.png', 'The Iceberg', 'Frost Blue', '#87CEEB'),
('The Iceberg (Maroon) w. Ice Cap', 'Deep maroon Iceberg with Ice Cap. Sophisticated color that makes a statement.', 'Water Bottles', 'In Store', 'BO-34', 69.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-iceberg-maroon-w-ice-cap-bo34/', '/product-images/BO-34.png', 'The Iceberg', 'Maroon', '#800000'),
('The Iceberg (Orange) w. Ice Cap', 'Bright orange Iceberg with Ice Cap. Energetic color for those who live life boldly.', 'Water Bottles', 'In Store', 'BO-35', 69.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-iceberg-orange-w-ice-cap-bo35/', '/product-images/BO-35.png', 'The Iceberg', 'Orange', '#FFA500'),
('The Iceberg (White) w. Ice Cap', 'Clean white Iceberg with Ice Cap. Pure, minimalist design that represents clarity and performance.', 'Water Bottles', 'In Store', 'BO-36', 69.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-iceberg-white-w-ice-cap-bo36/', '/product-images/BO-36.png', 'The Iceberg', 'White', '#FFFFFF'),
('The Iceberg (Christmas Tree) w. Ice Cap', 'Festive Christmas tree Iceberg with Ice Cap. Holiday edition bringing cheer to your hydration.', 'Water Bottles', 'In Store', 'BO-37', 69.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-iceberg-christmas-tree-w-ice-cap-bo37/', '/product-images/BO-37.png', 'The Iceberg', 'Christmas Tree', '#228B22'),
('The Iceberg (Iced Cookie) w. Ice Cap', 'Sweet iced cookie Iceberg with Ice Cap. Limited edition holiday design.', 'Water Bottles', 'In Store', 'BO-38', 69.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-iceberg-iced-cookie-w-ice-cap-bo38/', '/product-images/BO-38.png', 'The Iceberg', 'Iced Cookie', '#DEB887'),
('The Iceberg (Rudolph Red) w. Ice Cap', 'Festive Rudolph red Iceberg with Ice Cap. Holiday cheer meets premium hydration.', 'Water Bottles', 'In Store', 'BO-39', 69.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-iceberg-rudolph-red-w-ice-cap-bo39/', '/product-images/BO-39.png', 'The Iceberg', 'Rudolph Red', '#FF0000'),
('The Iceberg (Santa''s Sleigh) w. Ice Cap', 'Magical Santa sleigh Iceberg with Ice Cap. Holiday wonderland in bottle form.', 'Water Bottles', 'In Store', 'BO-40', 69.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/the-iceberg-santas-sleigh-w-ice-cap-bo40/', '/product-images/BO-40.png', 'The Iceberg', 'Santa Sleigh', '#FF0000'),

-- Bundles
('Alo x Thrive Bundle', 'Premium collaboration bundle featuring Alo yoga essentials and Thrive hydration products. Ultimate wellness package for the mindful athlete.', 'Bundles', 'In Store', 'SE-F-1', 499.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/alo-x-thrive-bundle-sef1/', '/product-images/SE-F-1.png', 'Alo x Thrive Bundle', NULL, NULL),
('Peleton x Thrive Bundle', 'Elite fitness bundle combining Peleton equipment with Thrive hydration. Complete home gym solution with premium accessories.', 'Bundles', 'In Store', 'SE-F-2', 2999.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/peloton-x-thrive-bundle-sef2/', '/product-images/SE-F-2.png', 'Peleton x Thrive Bundle', NULL, NULL),
('Fall Bundle', 'Seasonal autumn collection with essential wellness products. Curated selection to support your active lifestyle during the fall months.', 'Bundles', 'In Store', 'SE-F-3', 399.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/fall-bundle-sef3/', '/product-images/SE-F-3.png', 'Fall Bundle', NULL, NULL),

-- Seasonal - Peak Protein Variants
('Peak Protein (Pumpkin Spice)', 'Seasonal pumpkin spice protein powder. Limited edition fall flavor with warm spices and premium protein blend.', 'Wellness', 'Removal Requested', 'SU-PR-3', 49.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/peak-protein-pumpkin-spice-supr3/', '/product-images/SU-PR-3.png', 'Peak Protein', 'Pumpkin Spice', '#D2691E'),
('Peak Protein (Gingerbread)', 'Festive gingerbread protein powder. Holiday spice blend with the same premium protein quality you expect.', 'Wellness', 'In Store', 'SU-PR-4', 49.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/peak-protein-gingerbread-supr4/', '/product-images/SU-PR-4.png', 'Peak Protein', 'Gingerbread', '#8B4513'),
('Peak Protein (Marshmallow)', 'Sweet marshmallow protein powder. Limited edition flavor that brings comfort to your post-workout routine.', 'Wellness', 'In Store', 'SU-PR-5', 49.99, 'https://portal.veinternational.org/buybuttons/us019814/btn/peak-protein-marshmallow-supr5/', '/product-images/SU-PR-5.png', 'Peak Protein', 'Marshmallow', '#E6E6FA');
